language: python
cache:
  directories:
    #- $HOME/.cache/pip
    #- $HOME/miniconda3
    - $HOME/.config/sequana

matrix:
  include:
    - python: 3.5
    - python: 3.6

before_install:

    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda3/bin:$PATH
    - hash -r
    - conda update --yes conda
    - conda config --add channels r
    - conda config --add channels defaults
    - conda config --add channels conda-forge
    - conda config --add channels bioconda
    # This help testing code with pylab
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install:
  - echo $TRAVIS_PYTHON_VERSION
  - conda create --yes --name testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv

  - conda install --yes --file requirements.txt
  - conda install --yes --file requirements_dev.txt
  # ideally, we should use requirements_pipelines but this lead to stall on
  # travis because of many dependencies. For testing, we only need those ones
  - conda install --yes kraken bwa snpeff shustring krona sambamba
  - conda install --yes picard pigz cutadapt fastqc
  - conda install --yes freebayes --no-deps
  #- conda install --yes pysam samtools --no-deps 

  #- conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements_pipelines.txt
  - pip install .

# # command to run tests, e.g. python setup.py test
script:
  - pytest -v --durations=10  test/ --cov=sequana --cov-report term --timeout 300 -n 4

after_success:
  coveralls
