# ============================================================================
# Config file for ATAC-seq
#
# ==========================================[ Sections for the users ]========
#
# One of input_directory, input_pattern and input_samples must be provided
# If input_directory provided, use it otherwise if input_pattern provided,
# use it, otherwise use input_samples.
# If input_extension provided, use it otherwise assume fastq.gz
# ============================================================================
input_directory: "%(input_directory)s"
input_pattern: "%(input_pattern)s"
input_extension: "%(input_extension)s"
# =========================================== Sections for the users

# list of your input file
input_samples:
    file1: "%(file1)s"
    file2: "%(file2)s"

# if files are required for a pipeline and are within sequana or should
# # be downloaded before the pipeline provide them in this section
# # Note that sequana and url fields are followed by itemised files or links
# using
# # the front dashes
requirements:
    - phiX174.fa
    - Institut_Pasteur.png

# =========================================== Sections related to external tools
fastqc:
    options: "--nogroup"

##################################################################
#       MAPPING SECTION
#     Don't forgot to fill sequencing information
##################################################################
sequencing:
    platform: "Illumina"
    instrument: "Hiseq2500"
    flowcell: "H35CTBCXY"


bowtie2_mapping:
    do: yes
    prefix_index: /pasteur/projets/specific/PF2_ngs/protected/bowtie2_genomes/cryptNeo
    #options: "--dovetail --no-mixed --no-discordant " ##for paired-end data
    options: ""
    threads: 4


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Mark duplicates (picard-tools)

mark_duplicates:
    remove: 'True' ## may be False
    tmpdir: 'TMP_DIR=/local/scratch/' ## on Slurm cluster at Pasteur

##################################################################
#       PEAK CALLING SECTION
#     Go to https://github.com/taoliu/MACS for more explanation
##################################################################
macs2:
    genomeSize: "mm"
    readLength: 100
    qval: 0.1 ## cutoff on q-value
    options: ""

#################################################################
# Quality trimming and adapter removal
#   - quality: 0 means no trimming, 30 means keep base with quality
#       above 30
#   - m: 20 means discard trimmed reads that are shorter than 20.
#   - tool: only cutadapt supported for now
#   ref: http://cutadapt.readthedocs.io/
#################################################################
adapter_removal:
    do: yes
    tool: cutadapt
    design: "%(adapter_design)s"
    adapter_type: "%(adapter_type)s"
    fwd: "%(adapter_fwd)s"
    rev: "%(adapter_rev)s"
    m: 20   # min length cutoff
    M: 120  # max length cutoff
    mode: "g"   # g for 5' adapter, a for 3' and b for both 5'/3'
    quality: "30"
    options: "-O 6 --trim-n"

##################################################################
#       REPORTING SECTION WITH MULTIQC
#
##################################################################

multiqc:
    excluded: "-x *_init_* -x *left_kept_reads* -x *report_atac-seq*"
    output-directory: "multiqc"




##### DEEPTOOLS SECTION

correlation:
    binSize: 10000
    type: "scatterplot"
    metyhode: "pearson"

coverage:
    binSize: 10
    genomeSize: 121400000
    fragmentLength: 120

